### ISSUE TITLE
Challenge details

### ISSUE THREAD

**Issue by vladie0** [causalbench/causalbench-starter#1]
Dear, 

The GSK challenge has started on the 1th of March but I'm failing to see the data, instruction and code to actually get started. 

Do you have a foresight on when this will become available? 

KR.

**Comment by causalbench** [comment]
Thank you very much for your interest!

Details regarding the challenge will be published in the coming days as indicated in the README.md.

In the meantime, we recommend familiarising yourself with the problem by having a look at the literature: https://arxiv.org/abs/2210.17283
https://papers.nips.cc/paper/2020/hash/f8b7aa3a0d349d9562b424160ad18612-Abstract.html
https://arboreto.readthedocs.io/en/latest/
https://www.sciencedirect.com/science/article/pii/S0092867422005979#da0010

Very much looking forward to your submission!

**Comment by causalbench** [comment]
dear @vladie0 and participants, we released the full repository today. Looking forward to your submissions - happy coding!
