### ISSUE TITLE
Modifications of the baselines

### ISSUE THREAD

**Issue by imgremlin** [causalbench/causalbench-starter#2]
> For this challenge, you are restricted to use one of the two functions that are given to you. Almost any modifications are allowed, even though the final algorithm should remain close in essence to the baseline method. You can also directly modify the algorithm. For example, you could write new probability distribution estimators for DCDI like [here](https://github.com/causalbench/causalbench/tree/master/causalscbench/third_party/dcdi/dcdi/models). All your code needs to be in /src, either directly in e.g. dcdi.py or as subpackages, and should run properly using the above command. See the section below expliciting more rules and information on what modification are allowed or not.

How far can we go from the baseline? For example, are we allowed to use our embeddings with DCDI?

**Comment by jeskowagner** [comment]
I would also like the answer to this. Also, is there any leeway to go beyond the two implemented methods? We believe to have some good ideas how to infer better causal graphs. The phrasing
> Almost any modifications are allowed, even though the final algorithm should remain close in essence to the baseline method. You can also directly modify the algorithm.

is a bit ambigous.

**Comment by causalbench** [comment]
Thank you for your request. We're glad to hear that you already have creative improvement ideas!

> How far can we go from the baseline? For example, are we allowed to use our embeddings with DCDI?

> Also, is there any leeway to go beyond the two implemented methods? We believe to have some good ideas how to infer better causal graphs. 

The challenge is open to different approaches and ideas, and thus baselines can be modified at will (under the limitations outlined in the challenge rules). The limitations are the ones listed in the README - which include that no external data can be used. Utilising embeddings trained on another dataset therefore is not permitted. 

Also note that while we encourage participants to be creative and explore various techniques, please do keep in mind that larger modifications may require more time to implement from scratch and get to the performance level that existing methods achieve, and hence may put you at a disadvantage.

If you have any further questions or need additional clarification, please don't hesitate to ask or reach out.
