### ISSUE TITLE
CORUM data download problem

### ISSUE THREAD

**Issue by mkowiel** [causalbench/causalbench-starter#4]
The benchmark script shows **Timeout error** while downloading `humanComplexes.txt.zip` file  from  `https://mips.helmholtz-muenchen.de/corum/download/releases/current/humanComplexes.txt.zip`

**Comment by causalbench** [comment]
Thank you @mkowiel for reporting this issue. 
It appears `https://mips.helmholtz-muenchen.de/corum` is currently experiencing some downtime. 

Should the servers still be offline on Monday, we will attempt to make a mirror link available for this file if the licensing terms permit us to do so.

**Comment by jeskowagner** [comment]
Just to add that [Helmholtz reports](https://www.helmholtz-munich.de/en/) that they have been hit by a cyberattack on the 15th. To quote: "On 15 March 2023, a cyberattack from an external source was detected at Helmholtz Munich. As a result, the research center based in Munich-Neuherberg has taken extensive defensive measures. Recommended primary means of contact for partners are phone-based communication channels until further notice." I am guessing this to be the source of the downtime.

**Comment by mkowiel** [comment]
Could somebody share a file, I don't have it cached so I can't run the experiments

**Comment by causalbench** [comment]
@mkowiel Thank you. We updated [causalbench](https://github.com/causalbench/causalbench) to use a mirror for this file. You will need to upgrade your causalbench to 1.0.1 using `pip install --upgrade --force-reinstall causalbench`.

**Comment by sibasmarak** [comment]
@causalbench 
The requirements.txt file still contains `causalbench==1.0.0`. 
Could you update it so that future users (participants) would not face this error (if it exists for a longer time)? Thanks!
